config/routes.rb
Rails.application.routes.draw do
  resources :deals
  resources :categories
  devise_for :users
  authenticated :user do
    root to: 'categories#index', as: :authenticated_root
  end
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "home#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user.present?

    can :manage, Deal, author: user
    can :manage, Category, user: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_one_attached :icon # For Active Storage
  has_and_belongs_to_many :deals
  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    deals.sum('amount')
  end
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :email, presence: true
  validates :email, uniqueness: true
  has_many :categories
  has_many :deals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!
  # GET /categories or /categories.json
  def index
    @categories = current_user.categories.order(created_at: 'desc')
  end

  # GET /categories/1 or /categories/1.json
  def show
    puts @category.inspect
    @deals = @category.deals.order(created_at: 'desc')
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]
  # GET /deals or /deals.json
  def index
    @deals = @categories.deals.order(created_at: 'desc')
  end

  def new
    @deal = Deal.new
  end

  # POST /deals or /deals.json
  def create
    @deal = Deal.new(deal_params)
    puts "Deal = #{@deal.inspect}"
    @deal.author_id = current_user.id
    puts "Deal = #{@deal.inspect}"
    respond_to do |format|
      if @deal.save
        if @deal.categories.present?
          format.html { redirect_to @deal.categories.first, notice: 'Transaction was successfully added.' }
        else
          format.html do
            redirect_to root_path,
                        notice: 'Transaction was successfully added, but no category is associated with the deal.'
          end
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1 or /deals/1.json
  # def destroy
  #   @deal.destroy

  #   respond_to do |format|
  #     format.html { redirect_to  @deal.categories.first, notice: "Deal was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_deal
  #   @deal = Deal.find(params[:id])
  # end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/categories/_category.html.erb
<%= link_to category_url(category) do %>
  <div class="p-2 mb-3 flex justify-between items-center border bg-white border-3 shadow-lg rounded">
    <div class="flex items-center">
      <% if category.icon.present? %>
        <%= image_tag category.icon, class: "image w-20 h-20 mr-2" %>
      <% end %>
      <div>
          <h3 class="font-bold capitalize" style= 'color: #6b737d;'><%= category.name %></h3>
          <p style= 'color: #6b737d; margin-top: 0.7rem;'><%= category.created_at.strftime("%d %b %Y") %></p>
      </div>
    </div>
    <p class="font-bold" style= 'color: #434b54;'>$<%= category.total_amount %></p>
  </div>
<%end%>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5 px-2">
    <%= form.text_field :name,
        placeholder: "Category name",
        class: "text-sm text-gray-base w-full py-5 px-4 h-2 border border-gray-200 rounded mb-2"
    %>

    <%= form.file_field :icon,
        placeholder: "Icon",
        class: "text-sm text-gray-base w-full py-5 px-4 h-2 border border-gray-200 rounded mb-2"
    %>

    <% if category.icon.present? %>
      <p>Current Icon: <%= image_tag category.icon, class: "image w-20 h-20" %></p>
    <% end %>
    
    <%= form.number_field :user_id,
        id: :category_user_id,
        placeholder: "Athor id",
        value: current_user.id,
        type: :hidden,
        class: "text-sm text-gray-base w-full py-5 px-4 h-2 border border-gray-200 rounded mb-2"
    %>
  </div>

  <div class="absolute bottom-0 left-0 w-full py-3 px-5" style= 'background-color: #3778c2;'>
    <%= form.submit class: "w-full uppercase p-3 border-solid border-2 border-light-white-500 py-3 px-5 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/categories/_header.html.erb
<div class="w-full flex justify-between items-center text-white p-2" style= 'background-color: #3778c2;'>
  <i class="fa-solid fa-house"></i>
  <h2 class="uppercase">categories</h2>
  <%= link_to "", destroy_user_session_path, method: :delete, class: "fa-solid fa-right-from-bracket" %>
</div>

app/views/categories/index.html.erb
<div class="w-full h-screen relative overflow-y-auto bg-purple-100">
  <% if notice.present? %>
    <p class="absolute bottom-0 left-0 py-2 px-3 bg-green-50 mb-5 font-medium rounded-lg inline-block" style= 'color: #5fb523;' id="notice"><%= notice %></p>
  <% end %>

  <%= render "header" %>

  <div class="fixed w-screen bottom-0 left-0 p-4" style= 'background-color: #5fb523;'>
    <%= link_to 'scan',
        new_category_path,
        class: "uppercase w-full p-3 border-solid border-2 border-light-white-500  text-white block font-medium flex justify-center items-center py-3 px-5" %>
  </div>

  <div id="categories" class="p-3">
    <%= render @categories %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="w-full flex justify-between items-center text-white p-2" style= 'background-color: #3778c2;'>
    <i class=""></i>
    <h2 class="uppercase">add categories</h2>
    <%= link_to "Back", categories_path, class: "uppercase text-xs" %>
  </div>

  <%= render "form", category: @category, class: "mt-5" %>
</div>

app/views/categories/show.html.erb
<div class="w-full overflow-y-auto flex flex-col">
  <div class="w-full flex justify-between items-center text-white p-2" style= 'background-color: #3778c2;' >
    <%= link_to "", categories_path, class: "fa-solid fa-chevron-left" %>
    <h2 class="uppercase"><%= @category.name %>2</h2>
    <i></i>
  </div>
  <div class="flex w-full justify-between items-center p-3 border-b-2 border-gray-200">
    <p class="font-thin">Total amount: </p>
    <p class="font-semibold">$<%= @category.total_amount.round(2) %></p>
  </div>
  <div class="w-full flex flex-col p-1">

  <%= render 'deals/index', locals: { deals: @deals } %>

  </div>
  <div class="fixed w-screen bottom-0 left-0 p-4" style= "background-color: #5fb523;">
    <%= link_to 'Add new Deal',
        new_deal_path,
        class: "uppercase w-full p-3 border-solid border-2 border-light-white-500 text-white block font-medium flex  justify-center items-center py-3 px-5" %>
  </div>
</div>

app/views/deals/_deal.html.erb
<div id="<%= dom_id deal %>" class="w-full flex justify-between items-center border border-t-0 p-2 my-3">
  <div class="">
    <strong class="block font-medium mb-1" style= 'color: #6b737d;'><%= deal.name %></strong>
    <p style= 'color: #6b737d;'><%= deal.created_at.strftime("%d %b %Y")%></p>
  </div>

  <p class="">
    <strong class="block font-medium mb-1" style= 'color: #434b54;'>$<%= deal.amount %></strong>
  </p>
</div>

app/views/deals/_form.html.erb
<%= form_with(model: deal, class: "contents") do |form| %>
  <div class="w-full flex justify-between items-center text-white p-2" style= 'background-color: #3778c2;'>
    <%= link_to "", url_for(:back), class: "fa-solid fa-chevron-left" %>
    <h2 class="uppercase">Transaction</h2>
    <i></i>
  </div>
  <% if deal.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
        <% deal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-2">
    <%= form.text_field :name, placeholder: "Deal name", class: "text-sm text-gray-base w-full py-5 px-4 h-2 border border-gray-200 rounded mb-2" %>
    <%= form.text_field :amount, placeholder: "Amount", class: "text-sm text-gray-base w-full py-5 px-4 h-2 border border-gray-200 rounded mb-2" %>
    <%= form.collection_select :category_ids, current_user.categories.order(:name), :id, :name, {}, { class: "input w-full text-sm text-gray-base py-5 px-4 border border-gray-200 rounded mb-2", multiple: true } %>
  </div>

  <div class="absolute bottom-0 left-0 w-full py-3 px-5 " style= 'background-color: #3778c2;'>
    <%= form.submit class: "w-full uppercase p-3 border-solid border-2 border-light-white-500 py-3 px-5 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/deals/_index.html.erb
<div class="w-full">

  <div id="deals" class="w-full">
    <%= render @deals %>
  </div>
</div>

app/views/deals/new.html.erb
<div class="mx-auto md:w-2/3 w-full">

  <%= render "form", deal: @deal %>

</div>

app/views/deals/show.html.erb
<div class="w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @deal %>

    <%= link_to 'Edit this deal', edit_deal_path(@deal), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this deal', deal_path(@deal), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to deals', deals_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="h-screen flex flex-col items-center justify-center">
    <div class="self-auto text-3xl font-bold" style= 'color: #3778c2;'>
        <%= image_tag('logo.svg', alt: 'Cash Byte Logo', style: 'height: 100px;') %>
    </div>
    <div class="absolute bottom-0 left-0 flex flex-col justify-center items-center w-full px-1" >
        <%= link_to "LOG IN",
            new_user_session_path,
            class: "py-2 mx-2 rounded-md w-full text-center uppercase text-white", style: 'background-color: #3778c2' %>
        <%= link_to "SIGN UP",
            new_user_registration_path,
            method: :get,
            class: "py-2 rounded-md mt-1 mx-2 w-full text-center uppercase text-text-100", style: 'color: #6b737d' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/8f76becb1e.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen relative bg-white-700">
    <% if notice.present? %>
      <div class="w-full bg-green-500 text-white flex justify-center items-center">
        <p class="notice p-1 fw-regular"><%= notice %></p>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="w-full bg-red-500 text-white flex  justify-center items-center">
        <p class="alert p-1 fw-regular"><%= alert %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>